#!/bin/bash

# Um die Entwicklung und Fehlersuche zu vereinfachen, wird der Großteil des Tool-Runners
# in ein Python-Skript ausgelagert. Dieses kann einzeln getestet und debugged werden.
# Am Ende des Python-Skripts wird (wie vom MIF gefordert) der Pfad zu einer Datei an die
# Komandozeile übergeben. In dieser Datei lassen sich gefundene Klonpaare in der vom MIF
# geforderten Format finden.

# Der Systemname ist beim MIF immer `mutantbase`

# $1 = system directory 
# $2 = language {java, c, cs, py}
# $3 = frameowkr install dir
# $4 = tool dir
# $5 = fragmnet type (function|block)
# $6 = tool runner directory
# $7 = minlines

# Hier wird zum Ordner des Skripts gegangen, um es dann auszuführen
cd /media/MIF/dominator4java-mutation/scripts
python3 nicad_tool_runner.py $1 $2 $4 $5